name: Dependabot auto-merge
on:
  pull_request_target:

jobs:
  auto-merge:
    # see .github/auto-merge.yml for match configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        #if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.DEPENDABOT_SECRET }}"
          config: .github/auto-merge.yaml
      #- uses: "pascalgn/automerge-action@v0.14.2"
      #  env:
      #    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"