name: Dependabot auto-merge
on:
  pull_request_target:

jobs:
  auto-merge:
    # see .github/auto-merge.yml for match configuration
    runs-on: ubuntu-latest
    steps:
      - name: Get_name
        #run: echo ${{github.event_name}}
        #run: echo ${{github.actor}}
      if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: "${{ secrets.DEPENDABOT_SECRET }}"
          config: .github/auto-merge.yaml
      - uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
