name: Dependabot auto-merge
on:
  pull_request_target:
    paths-ignore:
      - gitops/terraform

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_NAME: ${{ github.event.pull_request.title }}
  GITHUB_ACTOR: ${{ github.event.pull_request.user.login }}

jobs:
  auto-merge:
    # see .github/auto-merge.yml for match configuration
    runs-on: ubuntu-latest
    steps:
    - name: View the PR number
      id: vpr
      run: |
        echo "PR number = ${{ github.event.pull_request.number }}"
        echo "PR number = ${{ env.PR_NUMBER }}"
        echo "PR name = ${{ github.event.pull_request.title }}"
        echo "PR name = ${{ env.PR_NAME }}"
        echo "PR actor = ${{ env.GITHUB_ACTOR }}"

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Automerge for other than node Dependencies
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      if: startsWith( !env.PR_NAME, 'Bump node' )
      with:
        github-token: "${{ secrets.DEPENDABOT_SECRET }}"
        config: .github/auto-merge.yaml

    - name: Automerge for node Dependencies
      if: startsWith( env.PR_NAME, 'Bump node' ) && env.GITHUB_ACTOR == 'dependabot[bot]'
      uses: "pascalgn/automerge-action@v0.14.2"
      env:
        GITHUB_TOKEN: "${{ secrets.DEPENDABOT_SECRET }}"
        MERGE_LABELS: dependencies